language: r
before_install:
  - cd source/PcAux

jobs:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: oldrel
    os: osx
  - r: release
    os: osx

sudo: false
